include:
  - remote: 'https://gitlab.com/cscs-ci/recipes/-/raw/master/templates/v2/.ci-ext.yml'

stages:
  - baseimage
  - build
  - test

build base uenv gh200:
  extends: .uenv-builder-daint-gh200
  stage: baseimage
  timeout: 2h
  variables:
    UENV_NAME: q-e-sirius-gh200
    UENV_RECIPE: .ci/uenv-recipe/
    UENV_VERSION: v1

build q-e-sirius cuda:
  extends: .uenv-runner-daint-gh200
  stage: build
  needs: ["build base uenv gh200"]
  image: q-e-sirius-gh200/v1:$CI_PIPELINE_ID
  artifacts:
    paths:
      - installdir.tar
  variables:
    SPEC: q-e-sirius@develop-ristretto
    CUDA_ARCH: 90
    REPO: ./.ci/uenv-recipe/repo
  script:
    - |
      #
      git clone --filter=tree:0 $(jq -r .spack.repo /user-environment/meta/configure.json) /dev/shm/spack-clone
      git -C /dev/shm/spack-clone checkout $(jq -r .spack.commit /user-environment/meta/configure.json)
      source /dev/shm/spack-clone/share/spack/setup-env.sh
      ./.ci/build-cuda.sh


.run_tests:
  stage: test
  extends: [.uenv-runner-daint-gh200]
  image: q-e-sirius-gh200/v1:$CI_PIPELINE_ID
  needs: ["build q-e-sirius cuda"]

  variables:
    SLURM_GPUS_PER_TASK: 1
    SLURM_CPU_BIND: 'socket'
    SLURM_HINT: nomultithread
    SLURM_WAIT: 0
    SLURM_TIMELIMIT: "30:00"
    USE_MPI: 'YES'
    WITH_UENV_VIEW: 'modules'

test (PW) CdO:
  extends: .run_tests
  variables:
    OMP_NUM_THREADS: $SLURM_CPUS_PER_TASK
    SIRIUS_PRINT_TIMING: 1
    SLURM_CPUS_PER_TASK: 20
    SLURM_NTASKS: 1
    SLURM_JOB_NUM_NODES: 1
  script:
    - ./ci/prepare-run.sh
    - export PATH=/dev/shm/spack-install/q-e-sirius-develop-ristretto/bin/:$PATH
    - module load python
    - cd ./ci-tests/CdO
    - pw.x -i CdO.in > out.txt
    - python3 ../qe_diff.py ref.txt out.txt

test (HP) ZrN:
  extends: .run_tests
  variables:
    OMP_NUM_THREADS: $SLURM_CPUS_PER_TASK
    SIRIUS_PRINT_TIMING: 1
    SLURM_CPUS_PER_TASK: 20
    SLURM_NTASKS: 1
    SLURM_JOB_NUM_NODES: 1
  script:
    - ./.ci/prepare-run.sh
    - export PATH=/dev/shm/spack-install/q-e-sirius-develop-ristretto/bin/:$PATH
    - cd ./ci-tests/ZrN
    - module load python
    - pw.x -i scf.in -use_qe_scf
    - hp.x -i hp.in
    - cat NZr.Hubbard_parameters.dat
    - python3 ../hp_diff.py hp.ref.yml hp.yml

test (HP) NW parallel:
  extends: .run_tests
  variables:
    OMP_NUM_THREADS: $SLURM_CPUS_PER_TASK
    SIRIUS_PRINT_TIMING: 1
    SLURM_CPUS_PER_TASK: 20
    SLURM_NTASKS: 4
    SLURM_JOB_NUM_NODES: 2
  script:
   - ./.ci/prepare-run.sh
   - export PATH=/dev/shm/spack-install/q-e-sirius-develop-ristretto/bin/:$PATH
   - ./ci-tests/NW/run_parallel.x

test (HP) FeO parallel:
  extends: .run_tests
  variables:
    OMP_NUM_THREADS: $SLURM_CPUS_PER_TASK
    SIRIUS_PRINT_TIMING: 1
    SLURM_CPUS_PER_TASK: 20
    SLURM_NTASKS: 4
    SLURM_JOB_NUM_NODES: 4
  script:
   - ./.ci/prepare-run.sh
   - export PATH=/dev/shm/spack-install/q-e-sirius-develop-ristretto/bin/:$PATH
   - ./ci-tests/FeO/run_parallel.x

test (HP) Mn2N2 parallel:
  extends: .run_tests
  variables:
    OMP_NUM_THREADS: $SLURM_CPUS_PER_TASK
    SIRIUS_PRINT_TIMING: 1
    SLURM_CPUS_PER_TASK: 20
    SLURM_NTASKS: 4
    SLURM_JOB_NUM_NODES: 1
  script:
   - ./.ci/prepare-run.sh
   - export PATH=/dev/shm/spack-install/q-e-sirius-develop-ristretto/bin/:$PATH
   - ./ci-tests/Mn2N2/run_parallel.x

test (HP) CaFeO2 parallel:
  extends: .run_tests
  variables:
    OMP_NUM_THREADS: $SLURM_CPUS_PER_TASK
    SIRIUS_PRINT_TIMING: 1
    SLURM_CONSTRAINT: gpu
    SLURM_CPUS_PER_TASK: 12
    SLURM_NTASKS: 4
    SLURM_JOB_NUM_NODES: 4
  script:
   - ./.ci/prepare-run.sh
   - export PATH=/dev/shm/spack-install/q-e-sirius-develop-ristretto/bin/:$PATH
   - ./ci-tests/CaFeO2/run_parallel.x

test (HP) NiO parallel:
  extends: .run_tests
  variables:
    OMP_NUM_THREADS: $SLURM_CPUS_PER_TASK
    SIRIUS_PRINT_TIMING: 1
    SLURM_CONSTRAINT: gpu
    SLURM_CPUS_PER_TASK: 12
    SLURM_NTASKS: 4
    SLURM_JOB_NUM_NODES: 4
  script:
   - ./.ci/prepare-run.sh
   - export PATH=/dev/shm/spack-install/q-e-sirius-develop-ristretto/bin/:$PATH
   - ./ci-tests/NiO/run_parallel.x

test (HP) LiCoO2:
  extends: .run_tests
  variables:
    OMP_NUM_THREADS: $SLURM_CPUS_PER_TASK
    SIRIUS_PRINT_TIMING: 1
    SLURM_CPUS_PER_TASK: 20
    SLURM_NTASKS: 1
    SLURM_JOB_NUM_NODES: 1
  script:
   - ./.ci/prepare-run.sh
   - export PATH=/dev/shm/spack-install/q-e-sirius-develop-ristretto/bin/:$PATH
   - cd ./ci-tests/LiCoO2
   - pw.x -i LiCoO2.scf.in -use_qe_scf
   - hp.x -i LiCoO2.hp.in
   - cat LiCoO2.Hubbard_parameters.dat
   - python3 ../hp_diff.py hp.ref.yml hp.yml

test (HP) LiCoO2 parallel:
  extends: .run_tests
  variables:
    OMP_NUM_THREADS: $SLURM_CPUS_PER_TASK
    SIRIUS_PRINT_TIMING: 1
    SLURM_CPUS_PER_TASK: 12
    SLURM_NTASKS: 4
    SLURM_JOB_NUM_NODES: 4
  script:
   - ./.ci/prepare-run.sh
   - export PATH=/dev/shm/spack-install/q-e-sirius-develop-ristretto/bin/:$PATH
   - cd ./ci-tests/LiCoO2
   - pw.x -i LiCoO2.scf.in -use_qe_scf
   - ./ci-tests/LiCoO2/run_parallel.x

# test (HP) Ni:
#   extends: .run_tests
#   variables:
#     OMP_NUM_THREADS: $SLURM_CPUS_PER_TASK
#     SIRIUS_PRINT_TIMING: 1
#     SLURM_CONSTRAINT: gpu
#     SLURM_CPUS_PER_TASK: 12
#     SLURM_NTASKS: 1
#     SLURM_JOB_NUM_NODES: 1
#   script:
#     - spack arch
#     - cd /qe-src/ci-tests/Ni
#     - /apps/bin/pw.x -i Ni.scf.in -use_qe_scf
#     - /apps/bin/hp.x -i Ni.hp.in
#     - cat Ni.Hubbard_parameters.dat
#     - python3 ../hp_diff.py hp.ref.yml hp.yml

# test (HP) Ni parallel:
#   extends: .run_tests
#   variables:
#     OMP_NUM_THREADS: $SLURM_CPUS_PER_TASK
#     SIRIUS_PRINT_TIMING: 1
#     SLURM_CONSTRAINT: gpu
#     SLURM_CPUS_PER_TASK: 12
#     SLURM_NTASKS: 3
#     SLURM_JOB_NUM_NODES: 3
#   script:
#     - /qe-src/ci-tests/Ni/run_parallel.x

# test (HP) CrI3 parallel:
#   extends: .run_tests
#   variables:
#     OMP_NUM_THREADS: $SLURM_CPUS_PER_TASK
#     SIRIUS_PRINT_TIMING: 1
#     SLURM_CONSTRAINT: gpu
#     SLURM_CPUS_PER_TASK: 12
#     SLURM_NTASKS: 4
#     SLURM_JOB_NUM_NODES: 4
#     SLURM_TIMELIMIT: "1:30:00"
#   script:
#     - /qe-src/ci-tests/CrI3/run_parallel.x
#     #- cd /qe-src/ci-tests/LiCoO2
#     #- /apps/bin/pw.x -i LiCoO2.scf.in -use_qe_scf -npool 2
#     #- /apps/bin/hp.x -i LiCoO2.hp.in -npool 2
#     - cat $PWD/CrI3/CrI3.Hubbard_parameters.dat
#     - python3 /qe-src/ci-tests/hp_diff.py /qe-src/ci-tests/CrI3/hp.ref.yml $PWD/CrI3/hp.yml

# test (KCW) Si:
#   extends: .run_tests
#   variables:
#     OMP_NUM_THREADS: $SLURM_CPUS_PER_TASK
#     SIRIUS_PRINT_TIMING: 1
#     SLURM_CONSTRAINT: gpu
#     SLURM_CPUS_PER_TASK: 12
#     SLURM_NTASKS: 1
#     SLURM_JOB_NUM_NODES: 1
#   script:
#     - cp -r /qe-src/ci-tests/Si_koopmans $PWD/Si_koopmans
#     - cd $PWD/Si_koopmans
#     - /apps/bin/pw.x -i Si.scf.in -use_qe_scf
#     - /apps/bin/wannier90.x -pp Si
#     - /apps/bin/pw2wannier90.x -i Si.pw2wann.in
#     - /apps/bin/wannier90.x Si
#     - cat Si.wout
#     - /apps/bin/wannier90.x -pp Si_emp
#     - /apps/bin/pw2wannier90.x -i Si_emp.pw2wann.in
#     - /apps/bin/wannier90.x Si_emp
#     - cat Si_emp.wout
#     - /apps/bin/kcw.x -i Si.kcw-wann2kcw.in
#     - /apps/bin/kcw.x -i Si.kcw-screen.in
#     - python3 /qe-src/ci-tests/kcw_diff.py /qe-src/ci-tests/Si_koopmans/kcw.ref.yml kcw.yml


# test (KCW) Si parallel:
#   extends: .run_tests
#   variables:
#     OMP_NUM_THREADS: $SLURM_CPUS_PER_TASK
#     SIRIUS_PRINT_TIMING: 1
#     SLURM_CONSTRAINT: gpu
#     SLURM_CPUS_PER_TASK: 12
#     SLURM_NTASKS: 4
#     SLURM_JOB_NUM_NODES: 4
#     SLURM_TIMELIMIT: "1:30:00"
#   script:
#     - /qe-src/ci-tests/Si_koopmans/run_parallel.x


# test (KCW) H2O parallel:
#   extends: .run_tests
#   variables:
#     OMP_NUM_THREADS: $SLURM_CPUS_PER_TASK
#     SIRIUS_PRINT_TIMING: 1
#     SLURM_CONSTRAINT: gpu
#     SLURM_CPUS_PER_TASK: 12
#     SLURM_NTASKS: 3
#     SLURM_JOB_NUM_NODES: 3
#   script:
#     - /qe-src/ci-tests/h2o_koopmans/run_parallel.x

# test (KCW) LiF parallel:
#   extends: .run_tests
#   variables:
#     OMP_NUM_THREADS: $SLURM_CPUS_PER_TASK
#     SIRIUS_PRINT_TIMING: 1
#     SLURM_CONSTRAINT: gpu
#     SLURM_CPUS_PER_TASK: 12
#     SLURM_NTASKS: 4
#     SLURM_JOB_NUM_NODES: 4
#     SLURM_TIMELIMIT: "1:30:00"
#   script:
#     - /qe-src/ci-tests/LiF_koopmans/run_parallel.x
