include:
  - remote: 'https://gitlab.com/cscs-ci/recipes/-/raw/master/templates/v2/.ci-ext.yml'

stages:
  - build
  - test

build image:
  extends: .container-builder
  stage: build
  timeout: 2h
  variables:
    DOCKERFILE: .ci/build.Dockerfile
    PERSIST_IMAGE_NAME: $CSCS_REGISTRY_PATH/q-e-sirius/q-e-sirius-ci:$CI_COMMIT_SHA
    #CSCS_REBUILD_POLICY: if-not-exists
    CSCS_REBUILD_POLICY: always

.run_tests:
  extends: .container-runner-daint-gpu
  needs: ["build image"]
  stage: test
  image: $CSCS_REGISTRY_PATH/q-e-sirius/q-e-sirius-ci:$CI_COMMIT_SHA
  variables:
    CRAY_CUDA_MPS: 1
    MPICH_MAX_THREAD_SAFETY: multiple
    SLURM_HINT: nomultithread
    SLURM_WAIT: 0
    SLURM_TIMELIMIT: "30:00"
    USE_MPI: 'YES'

test CdO:
  extends: .run_tests
  variables:
    OMP_NUM_THREADS: $SLURM_CPUS_PER_TASK
    SIRIUS_PRINT_TIMING: 1
    SLURM_CONSTRAINT: gpu
    SLURM_CPUS_PER_TASK: 12
    SLURM_NTASKS: 1
    SLURM_JOB_NUM_NODES: 1
  script:
    - cd /qe-src/ci-tests/CdO
    - /apps/bin/pw.x -i CdO.in > out.txt
    - python3 ../qe_diff.py ref.txt out.txt

test LiCoO2:
  extends: .run_tests
  variables:
    OMP_NUM_THREADS: $SLURM_CPUS_PER_TASK
    SIRIUS_PRINT_TIMING: 1
    SLURM_CONSTRAINT: gpu
    SLURM_CPUS_PER_TASK: 12
    SLURM_NTASKS: 1
    SLURM_JOB_NUM_NODES: 1
  script:
    - cd /qe-src/ci-tests/LiCoO2
    - /apps/bin/pw.x -i LiCoO2.scf.in -use_qe_scf
    - /apps/bin/hp.x -i LiCoO2.hp.in
    - cat LiCoO2.Hubbard_parameters.dat
