include:
  - remote: 'https://gitlab.com/cscs-ci/recipes/-/raw/master/templates/v2/.ci-ext.yml'

stages:
  - baseimage
  - build
  - test

build base cuda image:
  extends: .container-builder-dynamic-name
  stage: baseimage
  timeout: 2h
  variables:
    DOCKERFILE: .ci/baseimage.cuda.Dockerfile
    WATCH_FILECHANGES: .ci/baseimage.cuda.Dockerfile
    PERSIST_IMAGE_NAME: $CSCS_REGISTRY_PATH/base/q-e-sirius-ci
    DOCKER_BUILD_ARGS: '["CUDA_ARCH=60"]'

build cuda image:
  extends: .container-builder
  needs: ["build base cuda image"]
  stage: build
  timeout: 4h
  variables:
    DOCKERFILE: .ci/build.Dockerfile
    PERSIST_IMAGE_NAME: $CSCS_REGISTRY_PATH/q-e-sirius/q-e-sirius-ci:$CI_COMMIT_SHA
    DOCKER_BUILD_ARGS: '["BASE_IMAGE=${BASE_IMAGE}"]'

.run_tests:
  extends: .container-runner-daint-gpu
  needs: ["build cuda image"]
  stage: test
  image: $CSCS_REGISTRY_PATH/q-e-sirius/q-e-sirius-ci:$CI_COMMIT_SHA
  variables:
    CRAY_CUDA_MPS: 1
    MPICH_MAX_THREAD_SAFETY: multiple
    SLURM_HINT: nomultithread
    SLURM_WAIT: 0
    SLURM_TIMELIMIT: "30:00"
    USE_MPI: 'YES'

test CdO:
  extends: .run_tests
  variables:
    OMP_NUM_THREADS: $SLURM_CPUS_PER_TASK
    SIRIUS_PRINT_TIMING: 1
    SLURM_CONSTRAINT: gpu
    SLURM_CPUS_PER_TASK: 12
    SLURM_NTASKS: 1
    SLURM_JOB_NUM_NODES: 1
  script:
    - cd /qe-src/ci-tests/CdO
    - /apps/bin/pw.x -i CdO.in > out.txt
    - python3 ../qe_diff.py ref.txt out.txt

test ZrN:
  extends: .run_tests
  variables:
    OMP_NUM_THREADS: $SLURM_CPUS_PER_TASK
    SIRIUS_PRINT_TIMING: 1
    SLURM_CONSTRAINT: gpu
    SLURM_CPUS_PER_TASK: 12
    SLURM_NTASKS: 1
    SLURM_JOB_NUM_NODES: 1
  script:
    - cd /qe-src/ci-tests/ZrN
    - /apps/bin/pw.x -i scf.in -use_qe_scf
    - /apps/bin/hp.x -i hp.in
    - cat NZr.Hubbard_parameters.dat
    - python3 ../hp_diff.py hp.ref.yml hp.yml

test FeO parallel:
  extends: .run_tests
  variables:
    OMP_NUM_THREADS: $SLURM_CPUS_PER_TASK
    SIRIUS_PRINT_TIMING: 1
    SLURM_CONSTRAINT: gpu
    SLURM_CPUS_PER_TASK: 12
    SLURM_NTASKS: 4
    SLURM_JOB_NUM_NODES: 4
  script:
    - /qe-src/ci-tests/FeO/run_parallel.x

test CaFeO2 parallel:
  extends: .run_tests
  variables:
    OMP_NUM_THREADS: $SLURM_CPUS_PER_TASK
    SIRIUS_PRINT_TIMING: 1
    SLURM_CONSTRAINT: gpu
    SLURM_CPUS_PER_TASK: 12
    SLURM_NTASKS: 6
    SLURM_JOB_NUM_NODES: 6
  script:
    - /qe-src/ci-tests/CaFeO2/run_parallel.x

test LiCoO2:
  extends: .run_tests
  variables:
    OMP_NUM_THREADS: $SLURM_CPUS_PER_TASK
    SIRIUS_PRINT_TIMING: 1
    SLURM_CONSTRAINT: gpu
    SLURM_CPUS_PER_TASK: 12
    SLURM_NTASKS: 1
    SLURM_JOB_NUM_NODES: 1
  script:
    - cd /qe-src/ci-tests/LiCoO2
    - /apps/bin/pw.x -i LiCoO2.scf.in -use_qe_scf
    - /apps/bin/hp.x -i LiCoO2.hp.in
    - cat LiCoO2.Hubbard_parameters.dat
    - python3 ../hp_diff.py hp.ref.yml hp.yml

test LiCoO2 parallel:
  extends: .run_tests
  variables:
    OMP_NUM_THREADS: $SLURM_CPUS_PER_TASK
    SIRIUS_PRINT_TIMING: 1
    SLURM_CONSTRAINT: gpu
    SLURM_CPUS_PER_TASK: 12
    SLURM_NTASKS: 4
    SLURM_JOB_NUM_NODES: 4
  script:
    - /qe-src/ci-tests/LiCoO2/run_parallel.x

test Ni:
  extends: .run_tests
  variables:
    OMP_NUM_THREADS: $SLURM_CPUS_PER_TASK
    SIRIUS_PRINT_TIMING: 1
    SLURM_CONSTRAINT: gpu
    SLURM_CPUS_PER_TASK: 12
    SLURM_NTASKS: 1
    SLURM_JOB_NUM_NODES: 1
  script:
    - spack arch
    - cd /qe-src/ci-tests/Ni
    - /apps/bin/pw.x -i Ni.scf.in -use_qe_scf
    - /apps/bin/hp.x -i Ni.hp.in
    - cat Ni.Hubbard_parameters.dat
    - python3 ../hp_diff.py hp.ref.yml hp.yml

test Ni parallel:
  extends: .run_tests
  variables:
    OMP_NUM_THREADS: $SLURM_CPUS_PER_TASK
    SIRIUS_PRINT_TIMING: 1
    SLURM_CONSTRAINT: gpu
    SLURM_CPUS_PER_TASK: 12
    SLURM_NTASKS: 2
    SLURM_JOB_NUM_NODES: 2
  script:
    - spack arch
    - /qe-src/ci-tests/Ni/run_parallel.x
    - cat $PWD/Ni/Ni.Hubbard_parameters.dat
    - python3 /qe-src/ci-tests/hp_diff.py /qe-src/ci-tests/Ni/hp.ref.yml $PWD/Ni/hp.yml

test CrI3 parallel:
  extends: .run_tests
  variables:
    OMP_NUM_THREADS: $SLURM_CPUS_PER_TASK
    SIRIUS_PRINT_TIMING: 1
    SLURM_CONSTRAINT: gpu
    SLURM_CPUS_PER_TASK: 12
    SLURM_NTASKS: 4
    SLURM_JOB_NUM_NODES: 4
    SLURM_TIMELIMIT: "1:30:00"
  script:
    - /qe-src/ci-tests/CrI3/run_parallel.x
    #- cd /qe-src/ci-tests/LiCoO2
    #- /apps/bin/pw.x -i LiCoO2.scf.in -use_qe_scf -npool 2
    #- /apps/bin/hp.x -i LiCoO2.hp.in -npool 2
    - cat $PWD/CrI3/CrI3.Hubbard_parameters.dat
    - python3 /qe-src/ci-tests/hp_diff.py /qe-src/ci-tests/CrI3/hp.ref.yml $PWD/CrI3/hp.yml

test (KCW) Si serial:
  extends: .run_tests
  variables:
    OMP_NUM_THREADS: $SLURM_CPUS_PER_TASK
    SIRIUS_PRINT_TIMING: 1
    SLURM_CONSTRAINT: gpu
    SLURM_CPUS_PER_TASK: 12
    SLURM_NTASKS: 1
    SLURM_JOB_NUM_NODES: 1
  script:
    - cp -r /qe-src/ci-tests/Si_koopmans $PWD/Si_koopmans
    - cd $PWD/Si_koopmans
    - /apps/bin/pw.x -i Si.scf.in -use_qe_scf
    - /apps/bin/wannier90.x -pp Si
    - /apps/bin/pw2wannier90.x -i Si.pw2wann.in
    - /apps/bin/wannier90.x Si
    - cat Si.wout
    - /apps/bin/wannier90.x -pp Si_emp
    - /apps/bin/pw2wannier90.x -i Si_emp.pw2wann.in
    - /apps/bin/wannier90.x Si_emp
    - cat Si_emp.wout
    - /apps/bin/kcw.x -i Si.kcw-wann2kcw.in
    - /apps/bin/kcw.x -i Si.kcw-screen.in 
    - python3 /qe-src/ci-tests/hp_diff.py /qe-src/ci-tests/Si_koopmans/kcw.ref.yml kcw.yml


test (KCW) Si parallel:
  extends: .run_tests
  variables:
    OMP_NUM_THREADS: $SLURM_CPUS_PER_TASK
    SIRIUS_PRINT_TIMING: 1
    SLURM_CONSTRAINT: gpu
    SLURM_CPUS_PER_TASK: 12
    SLURM_NTASKS: 4
    SLURM_JOB_NUM_NODES: 4
    SLURM_TIMELIMIT: "1:30:00"
  script:
    - /qe-src/ci-tests/Si_koopmans/run_parallel.x
    - python3 /qe-src/ci-tests/hp_diff.py /qe-src/ci-tests/Si_koopmans/kcw.ref.yml $PWD/Si_koopmans_parallel/kcw.yml

test (KCW) H2O serial:
  extends: .run_tests
  variables:
    OMP_NUM_THREADS: $SLURM_CPUS_PER_TASK
    SIRIUS_PRINT_TIMING: 1
    SLURM_CONSTRAINT: gpu
    SLURM_CPUS_PER_TASK: 1
    SLURM_NTASKS: 1
    SLURM_JOB_NUM_NODES: 1
  script:
    - cp -r /qe-src/ci-tests/h2o_koopmans $PWD/h2o_koopmans
    - cd $PWD/h2o_koopmans
    - /apps/bin/pw.x -i h2o.scf.in -use_qe_scf
    - /apps/bin/kcw.x -i h2o.kcw-wann2kcw.in
    - /apps/bin/kcw.x -i h2o.kcw-screen.in 
    - python3 /qe-src/ci-tests/hp_diff.py /qe-src/ci-tests/h2o_koopmans/kcw.ref.yml kcw.yml

test (KCW) H2O parallel:
  extends: .run_tests
  variables:
    OMP_NUM_THREADS: $SLURM_CPUS_PER_TASK
    SIRIUS_PRINT_TIMING: 1
    SLURM_CONSTRAINT: gpu
    SLURM_CPUS_PER_TASK: 12
    SLURM_NTASKS: 4
    SLURM_JOB_NUM_NODES: 4
  script:
    - /qe-src/ci-tests/h2o_koopmans/run_parallel.x
    - python3 /qe-src/ci-tests/hp_diff.py /qe-src/ci-tests/h2o_koopmans/kcw.ref.yml $PWD/h2o_koopmans_parallel/kcw.yml
