include:
  - remote: 'https://gitlab.com/cscs-ci/recipes/-/raw/master/templates/v2/.ci-ext.yml'

stages:
  - build
  - test

build image:
  extends: .container-builder
  stage: build
  timeout: 2h
  variables:
    DOCKERFILE: .ci/build.Dockerfile
    PERSIST_IMAGE_NAME: $CSCS_REGISTRY_PATH/sirius/sirius-ci:$CI_COMMIT_SHA
    DOCKER_BUILD_ARGS: '["BASE_IMAGEIMAGE}", "SPECDEV=$SPEC"]'
